//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CityLibraryInfrastructure.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActionFiltersResource_tr_TR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionFiltersResource_tr_TR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CityLibraryInfrastructure.Resources.ActionFiltersResource_tr_TR", typeof(ActionFiltersResource_tr_TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string User_Name_Not_Exist {
            get {
                return ResourceManager.GetString("User_Name_Not_Exist", resourceCulture);
            }
        }
        
        internal static string Book_Not_Exist {
            get {
                return ResourceManager.GetString("Book_Not_Exist", resourceCulture);
            }
        }
        
        internal static string User_Name_Check {
            get {
                return ResourceManager.GetString("User_Name_Check", resourceCulture);
            }
        }
        
        internal static string Book_Not_Available {
            get {
                return ResourceManager.GetString("Book_Not_Available", resourceCulture);
            }
        }
    }
}
